
import { StyleSheet } from "react-native";

export default StyleSheet.create({
    scrollView: {
        flex: 1,
        backgroundColor: "#101820",
    },
    scrollContent: {
        flexGrow: 1,
    },
    container: {
        flex: 1,
        padding: 5,
        position: "relative",
    },
    glowTop: {
        position: "absolute",
        top: -100,
        left: -100,
        width: 300,
        height: 300,
        borderRadius: 150,
        backgroundColor: "rgba(255,196,0,0.15)",
        opacity: 0.6,
    },
    glowBottom: {
        position: "absolute",
        bottom: -150,
        right: -100,
        width: 350,
        height: 350,
        borderRadius: 175,
        backgroundColor: "rgba(255,196,0,0.1)",
        opacity: 0.4,
    },
    headerSection: {
        alignItems: "center",
        marginTop: 20,
    },
    iconContainer: {
        position: "relative",
        marginBottom: 20,
    },
    iconCircle: {
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: "#ffc40054",
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 3,
        borderColor: "#101820",
        shadowColor: "rgb(0, 255, 127)",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 20,
        elevation: 8,
    },
    iconGlow: {
        position: "absolute",
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: "rgba(255,196,0,0.3)",
        top: -5,
        left: -5,
    },
    iconText: {
        fontSize: 45,
    },
    appTitle: {
        fontSize: 32,
        fontWeight: "900",
        color: "rgb(0, 255, 127)",
        letterSpacing: 3,
        textShadowColor: "rgba(255,196,0,0.6)",
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 15,
        marginBottom: 5,
    },
    subtitle: {
        fontSize: 14,
        color: "rgb(0, 255, 127)",
        letterSpacing: 2,
        opacity: 0.8,
        textTransform: "uppercase",
    },
    divider: {
        width: 60,
        height: 3,
        backgroundColor: "rgb(0, 255, 127)",
        marginTop: 10,
        borderRadius: 2,
        shadowColor: "rgb(0, 255, 127)",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.8,
        shadowRadius: 10,
    },
    formSection: {
        backgroundColor: "#1a2332aa",
        borderRadius: 25,
        padding: 15,
        borderWidth: 1,
        borderColor: "rgba(255,196,0,0.2)",
        shadowColor: "rgb(0, 255, 127)",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 8,
    },
    formTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "rgb(0, 255, 127)",
        textAlign: "center",
        marginBottom: 25,
        letterSpacing: 1,
        textTransform: "uppercase",
    },
    inputWrapper: {
        marginBottom: 20,
    },
    inputRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 15,
    },
    inputHalf: {
        flex: 1,
    },
    labelRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    labelIcon: {
        fontSize: 16,
        marginRight: 8,
    },
    label: {
        fontSize: 12,
        fontWeight: "700",
        color: "rgb(0, 255, 127)",
        letterSpacing: 1,
    },
    input: {
        borderWidth: 2,
        borderColor: "rgba(255,196,0,0.3)",
        borderRadius: 12,
        padding: 15,
        fontSize: 16,
        backgroundColor: "#101820",
        color: "rgb(0, 255, 127)",
    },
    inputFocused: {
        borderColor: "rgb(0, 255, 127)",
        shadowColor: "rgb(0, 255, 127)",
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 8,
        elevation: 5,
    },
    inputDisabled: {
        opacity: 0.6,
        backgroundColor: "#0d1419",
    },
    textArea: {
        minHeight: 80,
        textAlignVertical: "top",
    },
    btn: {
        backgroundColor: "rgb(0, 255, 127)",
        paddingTop: 8,
        paddingBottom: 8,
        borderRadius: 15,
        marginTop: 10,
        position: "relative",
        overflow: "hidden",
        shadowColor: "rgb(0, 255, 127)",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.6,
        shadowRadius: 15,
        elevation: 10,
    },
    btnContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
    },
    btnText: {
        color: "#101820",
        fontSize: 18,
        fontWeight: "900",
        letterSpacing: 2,
    },
    btnArrow: {
        color: "#101820",
        fontSize: 24,
        fontWeight: "bold",
        marginLeft: 10,
    },
    btnGlow: {
        position: "absolute",
        width: "100%",
        height: "100%",
        backgroundColor: "rgba(255,255,255,0.2)",
        top: 0,
        left: 0,
    },
    securityNote: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginTop: 20,
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: "rgba(255,196,0,0.2)",
    },
    securityIcon: {
        fontSize: 14,
        marginRight: 8,
    },
    securityText: {
        color: "rgb(0, 255, 127)",
        fontSize: 12,
        opacity: 0.7,
    },
});